# Generated by Django 2.2 on 2020-10-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdata',
            name='category',
            field=models.CharField(default='unknown', max_length=200),
        ),
    ]
