# Generated by Django 2.2 on 2020-10-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20201026_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdata',
            name='image',
            field=models.ImageField(default='images/none/noimg.jpg', upload_to='images'),
        ),
    ]
